/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/ui/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseSegmented: typeof import('./components/ui/BaseSegmented.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RoleSwitch: typeof import('./components/auth/RoleSwitch.vue')['default']
    RoleSwitcher: typeof import('./components/RoleSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./components/UiButton.vue')['default']
    UiCheckbox: typeof import('./components/UiCheckbox.vue')['default']
    UiInput: typeof import('./components/UiInput.vue')['default']
    UiRoleSwitch: typeof import('./components/UiRoleSwitch.vue')['default']
  }
}
