"""moderator_comment

Revision ID: 96df300dfaa8
Revises: f2fd4537f0eb
Create Date: 2025-12-22 16:24:54.875078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96df300dfaa8'
down_revision: Union[str, Sequence[str], None] = 'f2fd4537f0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('moderator_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'moderator_comment')
    # ### end Alembic commands ###
